import "../../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AboutLayout = ({ children }) => {
  return (
    <div>
      <p className="ml-10">AboutLayout</p>
      {children}
    </div>
  );
};

export default AboutLayout;
