import "./globals.css";

export const metadata = {
  title: "Marketinglayout",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <p className="ml-5">RootLayout</p>
        {children}
      </body>
    </html>
  );
}
